Internal Server Error: /
Traceback (most recent call last):
  File "/mnt/c/Users/Noy/Dev/TWC-Ecommerce/src/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/mnt/c/Users/Noy/Dev/TWC-Ecommerce/src/TWC/middleware.py", line 37, in __call__
    if request.subdomain:
AttributeError: 'WSGIRequest' object has no attribute 'subdomain'
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/mnt/c/Users/Noy/Dev/TWC-Ecommerce/src/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/mnt/c/Users/Noy/Dev/TWC-Ecommerce/src/TWC/middleware.py", line 37, in __call__
    if request.subdomain:
AttributeError: 'WSGIRequest' object has no attribute 'subdomain'
